version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
    - 10.2.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 15.0.0
    - 15.0.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
    - 17.0.4
  - dependency-name: "@types/classnames"
    versions:
    - 2.3.1
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.10
    - 2.5.8
    - 2.5.9
  - dependency-name: animated-scroll-to
    versions:
    - 2.1.0
    - 2.2.0
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: dayjs
    versions:
    - 1.10.4
  - dependency-name: "@types/lodash"
    versions:
    - 4.14.168
  - dependency-name: ini
    versions:
    - 1.3.8
