name: website deploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get vars
        id: vars
        run: |
          echo "::set-output name=name::${GITHUB_REF#refs/*/}"
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
      
      - name: deploy
        id: deployment
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./
          alias-domains: |
            shokztv.micha.sh
            ${{ steps.vars.outputs.name }}.shokztv.micha.sh
            ${{ steps.vars.outputs.sha }}.shokztv.micha.sh
          
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          runs: 3
          urls: https://shokztv.micha.sh
          serverBaseUrl: ${{ secrets.LHCI_SERVER_URL }}
          serverToken: ${{ secrets.LHCI_SERVER_TOKEN }}